[package]
name = "autorun"
version = "1.0.1"
authors = ["Vurv78 <Vurv78@users.noreply.github.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["runner", "logging", "inject"]
runner = []
logging = ["chrono", "log", "simplelog"]
# Allow Autorun to also be injected through a DllMain export.
inject = []

[dependencies]
autorun-shared = { path = "../autorun-shared" }
rglua = { version = "3.0.0-beta" }

lua-patterns = "0.4"
detour = { version = "0.8.1", default-features = false }

# Error handling
human-panic = "1.0.3"
thiserror = "1.0.30"

# Settings
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"

# Global Mutable Variables
once_cell = "1.8.0"

# Misc
home = "0.5.3"
winapi = { version = "0.3.9", features = ["wincon", "consoleapi", "shellapi"] }
systrayx = "0.4.1"

# Logging
chrono = { version = "0.4.19", optional = true }
log = { version = "0.4.14", optional = true }
simplelog = { version = "0.11.2", optional = true }