[package]
name = "autorun"
version = "1.2.0-beta4"
authors = ["Vurv78 <Vurv78@users.noreply.github.com>"]
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["runner", "inject"]
runner = []
# Allow Autorun to also be injected through a DllMain export.
inject = []

[dependencies]
autorun-shared = { path = "../autorun-shared" }
rglua = { version = "3.0.0-beta" }

lua-patterns = "0.4"
detour = { version = "0.8.1", default-features = false }

# Error handling
human-panic = "1.0.3"
thiserror = "1.0.30"

# Settings
serde = { version = "1.0.136", features = ["derive"] }
toml = "0.5.8"

# Global Mutable Variables
once_cell = "1.10.0"

# Misc
home = "0.5.3"
winapi = { version = "0.3.9", features = ["wincon", "consoleapi", "shellapi"] }
systrayx = "0.4.1"

# Logging
chrono = "0.4.19"

colored = "2"

fs-err = "2.7.0"

# For ``requirebin``. This is already a dependency of ``rglua``, so no harm in adding it here.
libloading = "0.7.3"