[package]
name = "autorun-shared"
description = "Shared autorun functionality"
version = "0.1.1"
authors = ["Vurv78 <Vurv78@users.noreply.github.com>"]
edition = "2021"
publish = false

[features]
default = []