name: Download

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build DLL
      run: |
        rustup default nightly
        cd autorun
        cargo build --release --verbose
        cd ..

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: 64 Bit
        path: target/release/Autorun.dll

  buildgui64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build GUI
      run: |
        rustup default nightly
        cd autorun-gui
        cargo build --release --verbose
        cd ..

    - name: Upload EXE
      uses: actions/upload-artifact@v2
      with:
        name: 64 Bit
        path: target/release/autorun-gui.exe

  # In the future make this run on an x86 machine https://github.com/actions/runner/issues/423
  build86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build DLL
      run: |
        rustup default nightly
        rustup target add i686-pc-windows-msvc
        cd autorun
        cargo build --release --verbose --target=i686-pc-windows-msvc
        cd ..

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: 32 Bit
        path: target/i686-pc-windows-msvc/release/autorun.dll