name: Download

on:
  push:
    paths:
    - 'autorun/src/**'
    - 'autorun-shared/src/**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  upload64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build DLL
      run: |
        rustup default nightly
        cd autorun
        cargo build --release --verbose
        cd ..
        move target/release/autorun.dll gmsv_autorun_win64.dll

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: 64 Bit
        path: gmsv_autorun_win64.dll

  # In the future make this run on an x86 machine https://github.com/actions/runner/issues/423
  upload86:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build DLL
      run: |
        rustup default nightly
        rustup target add i686-pc-windows-msvc
        cd autorun
        cargo build --release --verbose --target=i686-pc-windows-msvc
        cd ..
        move target/i686-pc-windows-msvc/release/autorun.dll gmsv_autorun_win32.dll

    - name: Upload DLL
      uses: actions/upload-artifact@v2
      with:
        name: 32 Bit
        path: gmsv_autorun_win32.dll